name: resumen_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf
  assets:
    - assets/images/
