name: resumen_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.1
  google_fonts: ^4.0.4
  http: ^0.13.6
  icons_launcher: ^2.1.7
  syncfusion_flutter_pdfviewer: ^20.3.46
  url_launcher: ^6.0.20

icons_launcher:
  image_path: 'assets/images/iconLuncher.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf
  assets:
    - assets/images/
