import { useContext, useEffect, useRef, useState } from "react";
import { LoggedUserContext } from "../../../ActiveUserContext";
import server from "../../../Services/serverCall";
import "./WIP.css";
import ActiveWorkIndicator from "./ActiveWorkIndicator";
import ReadyWorkIndicator from "./ReadyWorkIndicator";
import { DBuser, LoggedUser } from "../../../Services/Types/UserTypes";
import { newUserTypesCorrections } from "../../../Services/updateLoggedUserFromDB";

function WIPindicator() {
  const activeUSer = useContext(LoggedUserContext);
  const intervalID = useRef<number[]>([]); /*This stores the id of the setInterval, to allow
   me to cancel it.
   I used an array, because as React renders everything twice while developing, I need to catch 
   IDs generated by both renders, and any other render triggered done by other processes.
   */
  const [showIsWorking, setShowIsWorking] = useState<boolean>(activeUSer.userState.inProgress);
  const checkServerStatus = useRef<boolean>(activeUSer.userState.inProgress);

  const checkInProgress = async () => {
    await server
      .get<boolean>(`/inprogress/${activeUSer.userState.id}`)
      .then((res) => {
        if (!res.data) {
          const update = async () => {
            await UpdateLoggedUserFromDB();
          };
          update();
        }
        return res;
      })
      .then((res) => {
        if (!res.data /*meanning "server has no work in progress"*/) {
          clearIntervals(); //If server is not working anymore, all setInterval() are stopped
          checkServerStatus.current = false;
          const newActiveUser: LoggedUser = { ...activeUSer.userState };
          newActiveUser.inProgress = false;
          activeUSer.userSteState(newActiveUser);
        }
        setShowIsWorking(res.data);
      })
      .catch((err) => console.log(err.error));
  };

  const clearIntervals = () => {
    while (intervalID.current.length != 0) {
      const removedElement = intervalID.current.pop();
      clearInterval(removedElement);
    }
  };

  const UpdateLoggedUserFromDB = async () => {
    await server
      .get<DBuser>(`/${activeUSer.userState.id}`)
      .then((res) => {
        const adjustedUser: LoggedUser = newUserTypesCorrections(res.data);
        activeUSer.userSteState(adjustedUser);
      })
      .catch((err) => {
        throw new Error(err.error);
      });
  };

  useEffect(() => {
    if (checkServerStatus.current) {
      setShowIsWorking(true);
      intervalID.current.push(setInterval(() => checkInProgress(), 3000));
    } else {
      checkServerStatus.current = true;
    }
  }, [activeUSer.userState.inProgress]);

  return <>{showIsWorking ? <ActiveWorkIndicator /> : <ReadyWorkIndicator />}</>;
}

export default WIPindicator;
